# ===============================
# CẤU HÌNH DATABASE (Dùng biến môi trường cho Aiven MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# CẤU HÌNH UPLOAD FILE
# ===============================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.resolve-lazily=true
spring.servlet.multipart.enabled=true

# ===============================
# CẤU HÌNH JWT
# ===============================
# Giấu secret key đi, sẽ cấu hình trên Render sau
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

server.address=0.0.0.0

# ===============================
# CẤU HÌNH EMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhphu25102005@gmail.com
# Giấu mật khẩu ứng dụng, sẽ cấu hình trên Render sau
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8080}